version: "3.9" 

services:
  redis:
    image: redis
    container_name: cache_TEST
    expose:
      - 6379

  app:
    build: 
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/var/www/app # docker workdir
    depends_on:
      - redis
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://cache_TEST
      - NODE_ENV=test
      - PORT=8000
    command: 
      sh -c 'npm run test:docker'
    