# Or whatever Node version/image you want
FROM node:lts

# Create app directory
WORKDIR '/var/www/app'

# Copy all files starts with package and ends wit .json 
COPY package*.json ./

# Install app dependencies
RUN apt update && apt install -y apt-transport-https ca-certificates sqlite3 libsqlite3-dev
RUN npm i 
RUN npm install -g sqlite3
RUN npm install -g sequelize-cli
RUN npm rebuild

# Copy all files from current directory to app directory
COPY . .

# Listen on port 8000
EXPOSE 8000

# Run the app
CMD [ "npm", "run", "dev" ]
